// REQ-4a: каталог магических предметов (DMG 2014). Грузится ЛЕНИВО через
// window.ensureMagicItems() (см. инлайн-загрузчик в index.html) — не входит в
// стартовый бандл. Используется пикером в модалке инвентаря (app-inventory.js).
//
// Схема записи:
//   { id, name, nameEn, rarity, type, attune, weight, desc, charges?, recharge? }
//   charges:  число зарядов (FIN-8) — предзаполняется в модалке инвентаря; опционально
//   recharge: "dawn" (по умолч.) | "none" — восстанавливаются ли на длинном отдыхе
//   rarity: "common" | "uncommon" | "rare" | "very_rare" | "legendary" | "artifact"
//   type:   "weapon" | "armor" | "shield" | "potion" | "ring" | "rod" |
//           "scroll" | "staff" | "wand" | "wondrous"
//   attune: false | true            (требуется ли настройка)
//   weight: число (фунты), 0 — пренебрежимо мал
//   desc:   краткое описание (1–2 предложения), RU
//
// Имена даны в распространённом переводе (Fantom Studio / dnd.su). nameEn — для
// поиска и на случай расхождений переводов; сверка названий — отдельная фаза REQ-5.
// rarityLabel/typeLabel — для UI пикера.
window.MAGIC_ITEM_RARITY = {
  common:    "обычный",
  uncommon:  "необычный",
  rare:      "редкий",
  very_rare: "очень редкий",
  legendary: "легендарный",
  artifact:  "артефакт"
};
window.MAGIC_ITEM_TYPE = {
  weapon:   "Оружие",
  armor:    "Доспех",
  shield:   "Щит",
  potion:   "Зелье",
  ring:     "Кольцо",
  rod:      "Жезл",
  scroll:   "Свиток",
  staff:    "Посох",
  wand:     "Волшебная палочка",
  wondrous: "Чудесный предмет"
};

window.MAGIC_ITEMS = [
  // ─── Зелья (Potions) ──────────────────────────────────────────────────────
  { id:"potion-healing",          name:"Зелье лечения",                     nameEn:"Potion of Healing",                 rarity:"common",    type:"potion", attune:false, weight:0.5, desc:"Восстанавливает 2к4+2 хитов при выпивании (действие)." },
  { id:"potion-greater-healing",  name:"Зелье большого лечения",            nameEn:"Potion of Greater Healing",         rarity:"uncommon",  type:"potion", attune:false, weight:0.5, desc:"Восстанавливает 4к4+4 хитов." },
  { id:"potion-superior-healing", name:"Зелье отличного лечения",           nameEn:"Potion of Superior Healing",        rarity:"rare",      type:"potion", attune:false, weight:0.5, desc:"Восстанавливает 8к4+8 хитов." },
  { id:"potion-supreme-healing",  name:"Зелье превосходного лечения",       nameEn:"Potion of Supreme Healing",         rarity:"very_rare", type:"potion", attune:false, weight:0.5, desc:"Восстанавливает 10к4+20 хитов." },
  { id:"potion-climbing",         name:"Зелье лазания",                     nameEn:"Potion of Climbing",                rarity:"common",    type:"potion", attune:false, weight:0.5, desc:"1 час даёт скорость лазания и преимущество на проверки лазания." },
  { id:"potion-water-breathing",  name:"Зелье подводного дыхания",          nameEn:"Potion of Water Breathing",         rarity:"uncommon",  type:"potion", attune:false, weight:0.5, desc:"1 час позволяет дышать под водой." },
  { id:"potion-fire-breath",      name:"Зелье огненного дыхания",           nameEn:"Potion of Fire Breath",             rarity:"uncommon",  type:"potion", attune:false, weight:0.5, desc:"До 3 раз за 1 час выдыхаете огонь на 4к6 урона (Лов половинит)." },
  { id:"potion-resistance",       name:"Зелье сопротивления",               nameEn:"Potion of Resistance",              rarity:"uncommon",  type:"potion", attune:false, weight:0.5, desc:"1 час сопротивление выбранному типу урона." },
  { id:"potion-heroism",          name:"Зелье героизма",                    nameEn:"Potion of Heroism",                 rarity:"rare",      type:"potion", attune:false, weight:0.5, desc:"1 час: 10 временных хитов и эффект «Героизм» (без концентрации)." },
  { id:"potion-invisibility",     name:"Зелье невидимости",                 nameEn:"Potion of Invisibility",            rarity:"very_rare", type:"potion", attune:false, weight:0.5, desc:"1 час невидимости (пока не атакуете/не сотворите заклинание)." },
  { id:"potion-flying",           name:"Зелье полёта",                      nameEn:"Potion of Flying",                  rarity:"very_rare", type:"potion", attune:false, weight:0.5, desc:"1 час скорость полёта, равная вашей скорости, и зависание." },
  { id:"potion-speed",            name:"Зелье скорости",                    nameEn:"Potion of Speed",                   rarity:"very_rare", type:"potion", attune:false, weight:0.5, desc:"1 минута эффекта «Ускорение» без концентрации." },
  { id:"potion-mind-reading",     name:"Зелье чтения мыслей",               nameEn:"Potion of Mind Reading",            rarity:"rare",      type:"potion", attune:false, weight:0.5, desc:"Эффект заклинания «Обнаружение мыслей»." },
  { id:"potion-diminution",       name:"Зелье уменьшения",                  nameEn:"Potion of Diminution",              rarity:"rare",      type:"potion", attune:false, weight:0.5, desc:"Эффект «уменьшения» из заклинания «Увеличение/уменьшение» на 1к4 часа." },
  { id:"potion-growth",           name:"Зелье увеличения",                  nameEn:"Potion of Growth",                  rarity:"uncommon",  type:"potion", attune:false, weight:0.5, desc:"Эффект «увеличения» на 1к4 часа." },
  { id:"potion-gaseous-form",     name:"Зелье газообразной формы",          nameEn:"Potion of Gaseous Form",            rarity:"rare",      type:"potion", attune:false, weight:0.5, desc:"Эффект заклинания «Газообразная форма» на 1 час." },
  { id:"potion-clairvoyance",     name:"Зелье ясновидения",                 nameEn:"Potion of Clairvoyance",            rarity:"rare",      type:"potion", attune:false, weight:0.5, desc:"Эффект заклинания «Ясновидение»." },
  { id:"potion-animal-friendship",name:"Зелье дружбы с животными",          nameEn:"Potion of Animal Friendship",       rarity:"uncommon",  type:"potion", attune:false, weight:0.5, desc:"Эффект «Дружба с животными» (Сл 13) на 1 час." },
  { id:"potion-poison",           name:"Зелье яда",                         nameEn:"Potion of Poison",                  rarity:"uncommon",  type:"potion", attune:false, weight:0.5, desc:"Маскируется под зелье лечения; 3к6 урона ядом и отравление (Тел Сл 13)." },
  { id:"potion-giant-strength-hill",  name:"Зелье силы холмовых великанов", nameEn:"Potion of Hill Giant Strength",  rarity:"uncommon",  type:"potion", attune:false, weight:0.5, desc:"1 час Сила становится 21." },
  { id:"potion-giant-strength-frost", name:"Зелье силы ледяных великанов",  nameEn:"Potion of Frost Giant Strength", rarity:"rare",      type:"potion", attune:false, weight:0.5, desc:"1 час Сила становится 23." },
  { id:"potion-giant-strength-stone", name:"Зелье силы каменных великанов", nameEn:"Potion of Stone Giant Strength", rarity:"rare",      type:"potion", attune:false, weight:0.5, desc:"1 час Сила становится 23." },
  { id:"potion-giant-strength-fire",  name:"Зелье силы огненных великанов", nameEn:"Potion of Fire Giant Strength",  rarity:"rare",      type:"potion", attune:false, weight:0.5, desc:"1 час Сила становится 25." },
  { id:"potion-giant-strength-cloud", name:"Зелье силы облачных великанов", nameEn:"Potion of Cloud Giant Strength", rarity:"very_rare", type:"potion", attune:false, weight:0.5, desc:"1 час Сила становится 27." },
  { id:"potion-giant-strength-storm", name:"Зелье силы штормовых великанов",nameEn:"Potion of Storm Giant Strength", rarity:"legendary", type:"potion", attune:false, weight:0.5, desc:"1 час Сила становится 29." },
  { id:"potion-vitality",         name:"Зелье живучести",                   nameEn:"Potion of Vitality",                rarity:"very_rare", type:"potion", attune:false, weight:0.5, desc:"Снимает истощение, болезни и яды; 24 часа кубики хитов и спас-бросок жизни максимальны." },
  { id:"oil-slipperiness",        name:"Масло скольжения",                  nameEn:"Oil of Slipperiness",               rarity:"uncommon",  type:"potion", attune:false, weight:0.5, desc:"8 часов эффект «Свободы перемещения»; или покрытие поверхности «Жиром»." },
  { id:"oil-sharpness",           name:"Масло остроты",                     nameEn:"Oil of Sharpness",                  rarity:"very_rare", type:"potion", attune:false, weight:0.5, desc:"1 час оружие/20 боеприпасов получают +3 к попаданию и урону." },
  { id:"oil-etherealness",        name:"Масло эфирности",                   nameEn:"Oil of Etherealness",               rarity:"rare",      type:"potion", attune:false, weight:0.5, desc:"Эффект «Этеричность» на 1 час." },
  { id:"keoghtom-ointment",       name:"Мазь Кеогтома",                     nameEn:"Keoghtom's Ointment",               rarity:"uncommon",  type:"potion", attune:false, weight:0.5, desc:"Банка на 5 доз: доза лечит 2к8+2 хитов и снимает яд/болезнь." },

  // ─── Свитки (Scrolls) ─────────────────────────────────────────────────────
  { id:"spell-scroll",            name:"Свиток заклинания",                 nameEn:"Spell Scroll",                      rarity:"common",    type:"scroll", attune:false, weight:0, desc:"Содержит одно заклинание; даёт сотворить его без ячейки (редкость зависит от уровня)." },
  { id:"scroll-protection",       name:"Свиток защиты",                     nameEn:"Scroll of Protection",              rarity:"rare",      type:"scroll", attune:false, weight:0, desc:"5 минут существа выбранного типа не могут приблизиться ближе 1,5 м." },

  // ─── Кольца (Rings) ───────────────────────────────────────────────────────
  { id:"ring-protection",         name:"Кольцо защиты",                     nameEn:"Ring of Protection",                rarity:"rare",      type:"ring", attune:true,  weight:0, desc:"+1 к КД и ко всем спасброскам." },
  { id:"ring-feather-falling",    name:"Кольцо падения пёрышком",           nameEn:"Ring of Feather Falling",           rarity:"rare",      type:"ring", attune:true,  weight:0, desc:"При падении опускаетесь медленно и не получаете урон от падения." },
  { id:"ring-free-action",        name:"Кольцо свободных действий",         nameEn:"Ring of Free Action",               rarity:"rare",      type:"ring", attune:true,  weight:0, desc:"Трудная местность не мешает; вас нельзя обездвижить или опутать." },
  { id:"ring-jumping",            name:"Кольцо прыжков",                    nameEn:"Ring of Jumping",                   rarity:"uncommon",  type:"ring", attune:true,  weight:0, desc:"Бонусным действием накладываете на себя «Прыжок»." },
  { id:"ring-mind-shielding",     name:"Кольцо защиты разума",              nameEn:"Ring of Mind Shielding",            rarity:"uncommon",  type:"ring", attune:true,  weight:0, desc:"Защита от чтения мыслей, определения мировоззрения и магического обнаружения." },
  { id:"ring-warmth",             name:"Кольцо тепла",                      nameEn:"Ring of Warmth",                    rarity:"uncommon",  type:"ring", attune:true,  weight:0, desc:"Сопротивление урону холодом; комфорт при температуре до −45 °C." },
  { id:"ring-water-walking",      name:"Кольцо хождения по воде",           nameEn:"Ring of Water Walking",             rarity:"uncommon",  type:"ring", attune:false, weight:0, desc:"Можно ходить по жидкой поверхности как по твёрдой земле." },
  { id:"ring-swimming",           name:"Кольцо плавания",                   nameEn:"Ring of Swimming",                  rarity:"uncommon",  type:"ring", attune:false, weight:0, desc:"Скорость плавания 12 м." },
  { id:"ring-resistance",         name:"Кольцо сопротивления",              nameEn:"Ring of Resistance",                rarity:"rare",      type:"ring", attune:true,  weight:0, desc:"Сопротивление одному типу урона (по типу самоцвета)." },
  { id:"ring-spell-storing",      name:"Кольцо хранения заклинаний",        nameEn:"Ring of Spell Storing",             rarity:"rare",      type:"ring", attune:true,  weight:0, desc:"Хранит до 5 уровней заклинаний для последующего сотворения." },
  { id:"ring-evasion",           name:"Кольцо уклонения",                  nameEn:"Ring of Evasion",                   rarity:"rare",      type:"ring", attune:true,  weight:0, charges:3, desc:"3 заряда: реакцией превратить проваленный спас Лов в успешный." },
  { id:"ring-x-ray-vision",       name:"Кольцо проникающего зрения",        nameEn:"Ring of X-ray Vision",              rarity:"rare",      type:"ring", attune:true,  weight:0, desc:"Действием видите сквозь твёрдые объекты на 9 м (с риском истощения)." },
  { id:"ring-telekinesis",        name:"Кольцо телекинеза",                 nameEn:"Ring of Telekinesis",               rarity:"very_rare", type:"ring", attune:true,  weight:0, desc:"По желанию накладываете «Телекинез»." },
  { id:"ring-spell-turning",      name:"Кольцо отражения заклинаний",       nameEn:"Ring of Spell Turning",             rarity:"legendary", type:"ring", attune:true,  weight:0, desc:"Преимущество против заклинаний, нацеленных только на вас; иногда отражает их." },
  { id:"ring-regeneration",       name:"Кольцо регенерации",                nameEn:"Ring of Regeneration",              rarity:"very_rare", type:"ring", attune:true,  weight:0, desc:"Восстанавливаете 1к6 хитов каждые 10 минут; отращиваете утраченные части тела." },
  { id:"ring-invisibility",       name:"Кольцо невидимости",                nameEn:"Ring of Invisibility",              rarity:"legendary", type:"ring", attune:true,  weight:0, desc:"Действием становитесь невидимым, пока не отмените." },
  { id:"ring-three-wishes",       name:"Кольцо трёх желаний",               nameEn:"Ring of Three Wishes",              rarity:"legendary", type:"ring", attune:false, weight:0, charges:3, recharge:"none", desc:"3 заряда: каждый позволяет сотворить «Исполнение желаний»." },

  // ─── Жезлы (Rods) ─────────────────────────────────────────────────────────
  { id:"immovable-rod",           name:"Неподвижный жезл",                  nameEn:"Immovable Rod",                     rarity:"uncommon",  type:"rod", attune:false, weight:2, desc:"Зафиксируйте в воздухе — удерживает до 3600 кг." },
  { id:"rod-pact-keeper-1",       name:"Жезл хранителя договора +1",        nameEn:"Rod of the Pact Keeper, +1",        rarity:"uncommon",  type:"rod", attune:true,  weight:2, desc:"Колдун: +1 к попаданию и Сл заклинаний; восстановление ячейки бонусным действием." },
  { id:"rod-pact-keeper-2",       name:"Жезл хранителя договора +2",        nameEn:"Rod of the Pact Keeper, +2",        rarity:"rare",      type:"rod", attune:true,  weight:2, desc:"Колдун: +2 к попаданию и Сл заклинаний; восстановление ячейки бонусным действием." },
  { id:"rod-pact-keeper-3",       name:"Жезл хранителя договора +3",        nameEn:"Rod of the Pact Keeper, +3",        rarity:"very_rare", type:"rod", attune:true,  weight:2, desc:"Колдун: +3 к попаданию и Сл заклинаний; восстановление ячейки бонусным действием." },
  { id:"rod-alertness",           name:"Жезл бдительности",                 nameEn:"Rod of Alertness",                  rarity:"very_rare", type:"rod", attune:true,  weight:2, desc:"+1 к инициативе и Внимательности; даёт ауру защиты союзникам." },
  { id:"rod-absorption",          name:"Жезл поглощения",                   nameEn:"Rod of Absorption",                 rarity:"very_rare", type:"rod", attune:true,  weight:2, desc:"Реакцией поглощает направленное на вас заклинание и копит уровни для своих ячеек." },
  { id:"rod-security",            name:"Жезл безопасности",                 nameEn:"Rod of Security",                   rarity:"very_rare", type:"rod", attune:false, weight:2, desc:"Переносит вас и спутников в безопасный райский полудом для отдыха." },
  { id:"rod-rulership",           name:"Жезл правления",                    nameEn:"Rod of Rulership",                  rarity:"rare",      type:"rod", attune:true,  weight:2, charges:1, desc:"1 заряд: до 8 часов очаровывает существа в радиусе 36 м (Мдр)." },
  { id:"rod-lordly-might",        name:"Жезл величественной мощи",          nameEn:"Rod of Lordly Might",               rarity:"legendary", type:"rod", attune:true,  weight:2, desc:"Булава-«швейцарский нож»: превращается в меч, копьё, лестницу и т.д." },

  // ─── Посохи (Staves) ──────────────────────────────────────────────────────
  { id:"staff-python",            name:"Посох питона",                      nameEn:"Staff of the Python",               rarity:"uncommon",  type:"staff", attune:true, weight:4, desc:"Действием превращается в гигантскую змею-союзника." },
  { id:"staff-adder",             name:"Посох гадюки",                      nameEn:"Staff of the Adder",                rarity:"uncommon",  type:"staff", attune:true, weight:4, desc:"Бонусным действием голова становится ядовитой змеёй (атака 1к6 + 3к6 ядом)." },
  { id:"staff-healing",           name:"Посох лечения",                     nameEn:"Staff of Healing",                  rarity:"rare",      type:"staff", attune:true, weight:4, desc:"Заряды на «Лечение ран», «Множественное лечение ран» и «Лечение болезней»." },
  { id:"staff-charming",          name:"Посох очарования",                  nameEn:"Staff of Charming",                 rarity:"rare",      type:"staff", attune:true, weight:4, desc:"Заряды на «Очарование личности», «Приказ» и «Понимание языков»." },
  { id:"staff-swarming-insects",  name:"Посох роя насекомых",               nameEn:"Staff of Swarming Insects",         rarity:"rare",      type:"staff", attune:true, weight:4, desc:"Заряды на рой насекомых (2к10 урона) и «Нашествие насекомых»." },
  { id:"staff-withering",         name:"Посох иссушения",                   nameEn:"Staff of Withering",                rarity:"rare",      type:"staff", attune:true, weight:4, desc:"Атака посохом + 2к10 некротического урона и помеха на проверки Силы/Телосложения." },
  { id:"staff-fire",              name:"Посох огня",                        nameEn:"Staff of Fire",                     rarity:"very_rare", type:"staff", attune:true, weight:4, desc:"Сопротивление огню; заряды на «Огненные ладони», «Огненная стена», «Огненный шар»." },
  { id:"staff-frost",             name:"Посох мороза",                      nameEn:"Staff of Frost",                    rarity:"very_rare", type:"staff", attune:true, weight:4, desc:"Сопротивление холоду; заряды на «Туман», «Ледяная буря», «Ледяная стена», «Конус холода»." },
  { id:"staff-thunder-lightning", name:"Посох грома и молнии",              nameEn:"Staff of Thunder and Lightning",    rarity:"very_rare", type:"staff", attune:true, weight:4, desc:"Атака посохом с зарядами молнии, грома, оглушения и удара." },
  { id:"staff-striking",          name:"Посох ударов",                      nameEn:"Staff of Striking",                 rarity:"very_rare", type:"staff", attune:true, weight:4, desc:"Магический посох +3; заряды добавляют до 3к6 силового урона к удару." },
  { id:"staff-woodlands",         name:"Посох леса",                        nameEn:"Staff of the Woodlands",            rarity:"rare",      type:"staff", attune:true, weight:4, desc:"+2 посох/Сл друидских заклинаний; заряды на природную магию и форму дерева." },
  { id:"staff-power",             name:"Посох силы",                        nameEn:"Staff of Power",                    rarity:"very_rare", type:"staff", attune:true, weight:4, desc:"+2 КД/спасброски/атаки и Сл; множество заклинаний и удар-«разлом»." },
  { id:"staff-magi",              name:"Посох магов",                       nameEn:"Staff of the Magi",                 rarity:"legendary", type:"staff", attune:true, weight:4, desc:"Поглощение заклинаний, +2 к атакам/Сл и обширный список могучих заклинаний." },

  // ─── Волшебные палочки (Wands) ────────────────────────────────────────────
  { id:"wand-magic-detection",    name:"Волшебная палочка обнаружения магии", nameEn:"Wand of Magic Detection",           rarity:"uncommon",  type:"wand", attune:false, weight:1, charges:3, desc:"3 заряда в день: накладывает «Обнаружение магии»." },
  { id:"wand-secrets",            name:"Волшебная палочка секретов",        nameEn:"Wand of Secrets",                   rarity:"uncommon",  type:"wand", attune:false, weight:1, charges:3, desc:"3 заряда: указывает на скрытую дверь или ловушку поблизости." },
  { id:"wand-magic-missiles",     name:"Волшебная палочка снарядов",        nameEn:"Wand of Magic Missiles",            rarity:"uncommon",  type:"wand", attune:false, weight:1, charges:7, desc:"7 зарядов: тратьте на «Волшебная стрела» (1 заряд = 1 уровень)." },
  { id:"wand-war-mage-1",         name:"Волшебная палочка боевого мага +1", nameEn:"Wand of the War Mage, +1",          rarity:"uncommon",  type:"wand", attune:true,  weight:1, desc:"+1 к попаданию атак заклинаниями; игнор укрытия в половину." },
  { id:"wand-web",                name:"Волшебная палочка паутины",         nameEn:"Wand of Web",                       rarity:"uncommon",  type:"wand", attune:true,  weight:1, charges:7, desc:"7 зарядов: накладывает «Паутина» (концентрация)." },
  { id:"wand-enemy-detection",    name:"Волшебная палочка обнаружения врагов", nameEn:"Wand of Enemy Detection",           rarity:"rare",      type:"wand", attune:true,  weight:1, charges:7, desc:"7 зарядов: указывает направление к ближайшим враждебным существам." },
  { id:"wand-fear",               name:"Волшебная палочка страха",          nameEn:"Wand of Fear",                      rarity:"rare",      type:"wand", attune:true,  weight:1, desc:"Заряды на ауру страха или конус устрашения (Мдр)." },
  { id:"wand-fireballs",          name:"Волшебная палочка огненных шаров",  nameEn:"Wand of Fireballs",                 rarity:"rare",      type:"wand", attune:true,  weight:1, charges:7, desc:"7 зарядов: «Огненный шар» (1 заряд = 3 уровень, +1 за уровень)." },
  { id:"wand-lightning-bolts",    name:"Волшебная палочка молний",          nameEn:"Wand of Lightning Bolts",           rarity:"rare",      type:"wand", attune:true,  weight:1, charges:7, desc:"7 зарядов: «Молния» (1 заряд = 3 уровень, +1 за уровень)." },
  { id:"wand-paralysis",          name:"Волшебная палочка паралича",        nameEn:"Wand of Paralysis",                 rarity:"rare",      type:"wand", attune:true,  weight:1, charges:7, desc:"7 зарядов: цель парализуется при провале спаса Телосложения." },
  { id:"wand-binding",            name:"Волшебная палочка сковывания",      nameEn:"Wand of Binding",                   rarity:"rare",      type:"wand", attune:true,  weight:1, desc:"Заряды на «Удержание существа» и сопротивление обездвиживанию." },
  { id:"wand-polymorph",          name:"Волшебная палочка превращения",     nameEn:"Wand of Polymorph",                 rarity:"very_rare", type:"wand", attune:true,  weight:1, charges:7, desc:"7 зарядов: накладывает «Превращение»." },
  { id:"wand-wonder",             name:"Волшебная палочка чудес",           nameEn:"Wand of Wonder",                    rarity:"rare",      type:"wand", attune:true,  weight:1, charges:7, desc:"7 зарядов: случайный, часто непредсказуемый магический эффект." },

  // ─── Оружие (Weapons) ─────────────────────────────────────────────────────
  { id:"weapon-plus-1",           name:"Оружие +1",                         nameEn:"Weapon, +1",                        rarity:"uncommon",  type:"weapon", attune:false, weight:0, desc:"+1 к броску атаки и урона этим магическим оружием." },
  { id:"weapon-plus-2",           name:"Оружие +2",                         nameEn:"Weapon, +2",                        rarity:"rare",      type:"weapon", attune:false, weight:0, desc:"+2 к броску атаки и урона этим магическим оружием." },
  { id:"weapon-plus-3",           name:"Оружие +3",                         nameEn:"Weapon, +3",                        rarity:"very_rare", type:"weapon", attune:false, weight:0, desc:"+3 к броску атаки и урона этим магическим оружием." },
  { id:"ammunition-plus-1",       name:"Боеприпасы +1",                     nameEn:"Ammunition, +1",                    rarity:"uncommon",  type:"weapon", attune:false, weight:0, desc:"+1 к атаке и урону; после попадания теряет магию." },
  { id:"weapon-vicious",          name:"Жестокое оружие",                   nameEn:"Vicious Weapon",                    rarity:"rare",      type:"weapon", attune:false, weight:0, desc:"При выпадении 20 на атаке наносит дополнительно 2к6 урона своего типа." },
  { id:"javelin-of-lightning",    name:"Метательное копьё молнии",          nameEn:"Javelin of Lightning",              rarity:"uncommon",  type:"weapon", attune:false, weight:2, desc:"Брошенный, превращается в молнию (4к6 урона электричеством)." },
  { id:"trident-fish-command",    name:"Трезубец командования рыбами",      nameEn:"Trident of Fish Command",           rarity:"uncommon",  type:"weapon", attune:true,  weight:4, desc:"Магический трезубец; заряды на «Подчинение зверя» против водных тварей." },
  { id:"flame-tongue",            name:"Язык пламени",                      nameEn:"Flame Tongue",                      rarity:"rare",      type:"weapon", attune:true,  weight:0, desc:"Бонусным действием воспламеняется: +2к6 урона огнём и свет." },
  { id:"frost-brand",             name:"Морозный клинок",                   nameEn:"Frost Brand",                       rarity:"very_rare", type:"weapon", attune:true,  weight:0, desc:"+1к6 урона холодом; сопротивление огню; гасит огни и светится у огня." },
  { id:"dragon-slayer",           name:"Убийца драконов",                   nameEn:"Dragon Slayer",                     rarity:"rare",      type:"weapon", attune:false, weight:0, desc:"Магический меч +1; +3к6 урона драконам." },
  { id:"giant-slayer",            name:"Убийца великанов",                  nameEn:"Giant Slayer",                      rarity:"rare",      type:"weapon", attune:false, weight:0, desc:"Магическое оружие +1; +2к6 великанам и шанс сбить их с ног." },
  { id:"sword-of-sharpness",      name:"Меч остроты",                       nameEn:"Sword of Sharpness",                rarity:"very_rare", type:"weapon", attune:true,  weight:0, desc:"При сильном попадании удваивает кубики урона; может отрубать конечности." },
  { id:"sword-of-wounding",       name:"Меч ранения",                       nameEn:"Sword of Wounding",                 rarity:"rare",      type:"weapon", attune:true,  weight:0, desc:"Наносит длящийся кровоточащий урон, снижающий макс. хиты до отдыха." },
  { id:"sword-life-stealing",     name:"Меч кражи жизни",                   nameEn:"Sword of Life Stealing",            rarity:"rare",      type:"weapon", attune:true,  weight:0, desc:"При 20 на атаке +3к6 некротического урона и временные хиты вам." },
  { id:"dancing-sword",           name:"Танцующий меч",                     nameEn:"Dancing Sword",                     rarity:"very_rare", type:"weapon", attune:true,  weight:0, desc:"Бонусным действием взмывает и атакует сам по вашей команде." },
  { id:"dwarven-thrower",         name:"Дварфский метатель",              nameEn:"Dwarven Thrower",                   rarity:"very_rare", type:"weapon", attune:true,  weight:2, desc:"Молот +3 с возвратом при броске; +урон, особенно великанам (только дварф)." },
  { id:"nine-lives-stealer",      name:"Вор девяти жизней",                 nameEn:"Nine Lives Stealer",                rarity:"very_rare", type:"weapon", attune:true,  weight:0, desc:"Меч +2; при 20 цель может мгновенно умереть (Тел Сл 15)." },
  { id:"oathbow",                 name:"Лук клятвы",                        nameEn:"Oathbow",                           rarity:"very_rare", type:"weapon", attune:true,  weight:2, desc:"Объявите «заклятого врага» — против него преимущество, +3к6 урона и др." },
  { id:"sun-blade",               name:"Солнечный клинок",                  nameEn:"Sun Blade",                         rarity:"rare",      type:"weapon", attune:true,  weight:0, desc:"Клинок света (как длинный меч +2); +урон нежити и яркий свет." },
  { id:"mace-of-disruption",      name:"Булава распада",                    nameEn:"Mace of Disruption",                rarity:"rare",      type:"weapon", attune:true,  weight:4, desc:"Меч... булава +0; +2к6 урона излучением нежити/исчадиям, страх или гибель." },
  { id:"mace-of-smiting",         name:"Булава кары",                       nameEn:"Mace of Smiting",                   rarity:"rare",      type:"weapon", attune:false, weight:4, desc:"+1 (+3 конструктам); при 20 крушит конструктов." },
  { id:"mace-of-terror",          name:"Булава ужаса",                      nameEn:"Mace of Terror",                    rarity:"rare",      type:"weapon", attune:true,  weight:4, charges:3, desc:"3 заряда: аура страха в радиусе 9 м (Мдр)." },
  { id:"berserker-axe",           name:"Топор берсерка",                    nameEn:"Berserker Axe",                     rarity:"rare",      type:"weapon", attune:true,  weight:0, desc:"Магический топор +1; в бою может вынудить впасть в ярость." },
  { id:"vorpal-sword",            name:"Меч головоруб",                     nameEn:"Vorpal Sword",                      rarity:"legendary", type:"weapon", attune:true,  weight:0, desc:"Меч +3, игнорирует сопротивление рубящему; при 20 отрубает голову." },
  { id:"defender",                name:"Защитник",                          nameEn:"Defender",                          rarity:"legendary", type:"weapon", attune:true,  weight:0, desc:"Меч +3; распределяйте бонус между атакой и КД каждый ход." },
  { id:"holy-avenger",            name:"Святой мститель",                   nameEn:"Holy Avenger",                      rarity:"legendary", type:"weapon", attune:true,  weight:0, desc:"Меч +3 паладина; +2к10 урона излучением исчадиям/нежити и аура защиты." },

  // ─── Доспехи и щиты (Armor & Shields) ─────────────────────────────────────
  { id:"armor-plus-1",            name:"Доспех +1",                         nameEn:"Armor, +1",                         rarity:"rare",      type:"armor", attune:false, weight:0, desc:"+1 к КД сверх базового доспеха." },
  { id:"armor-plus-2",            name:"Доспех +2",                         nameEn:"Armor, +2",                         rarity:"very_rare", type:"armor", attune:false, weight:0, desc:"+2 к КД сверх базового доспеха." },
  { id:"armor-plus-3",            name:"Доспех +3",                         nameEn:"Armor, +3",                         rarity:"legendary", type:"armor", attune:false, weight:0, desc:"+3 к КД сверх базового доспеха." },
  { id:"shield-plus-1",           name:"Щит +1",                            nameEn:"Shield, +1",                        rarity:"uncommon",  type:"shield", attune:false, weight:6, desc:"+1 к КД сверх обычного щита (то есть +3 всего)." },
  { id:"shield-plus-2",           name:"Щит +2",                            nameEn:"Shield, +2",                        rarity:"rare",      type:"shield", attune:false, weight:6, desc:"+2 к КД сверх обычного щита." },
  { id:"shield-plus-3",           name:"Щит +3",                            nameEn:"Shield, +3",                        rarity:"very_rare", type:"shield", attune:false, weight:6, desc:"+3 к КД сверх обычного щита." },
  { id:"adamantine-armor",        name:"Адамантиновый доспех",              nameEn:"Adamantine Armor",                  rarity:"uncommon",  type:"armor", attune:false, weight:0, desc:"Критические попадания по вам становятся обычными." },
  { id:"mithral-armor",           name:"Мифрильный доспех",                 nameEn:"Mithral Armor",                     rarity:"uncommon",  type:"armor", attune:false, weight:0, desc:"Лёгкий: снимает помеху на Скрытность и требование Силы." },
  { id:"armor-resistance",        name:"Доспех сопротивления",              nameEn:"Armor of Resistance",               rarity:"rare",      type:"armor", attune:true,  weight:0, desc:"Сопротивление одному типу урона." },
  { id:"mariners-armor",          name:"Доспех моряка",                     nameEn:"Mariner's Armor",                   rarity:"uncommon",  type:"armor", attune:false, weight:0, desc:"Скорость плавания; не тянет ко дну в воде." },
  { id:"elven-chain",             name:"Эльфийская кольчуга",               nameEn:"Elven Chain",                       rarity:"rare",      type:"armor", attune:false, weight:20, desc:"Кольчуга +1; считается лёгкой, можно носить без владения средними доспехами." },
  { id:"dwarven-plate",           name:"Латы дварфов",                    nameEn:"Dwarven Plate",                     rarity:"very_rare", type:"armor", attune:false, weight:65, desc:"Латы +2; реакцией противостоять толчку/сбиванию." },
  { id:"dragon-scale-mail",       name:"Доспех из драконьей чешуи",         nameEn:"Dragon Scale Mail",                 rarity:"very_rare", type:"armor", attune:true,  weight:45, desc:"Чешуйчатый +1; сопротивление урону цвета дракона и чутьё на драконов." },
  { id:"glamoured-studded-leather",name:"Красивый проклёпанный доспех",     nameEn:"Glamoured Studded Leather",         rarity:"rare",      type:"armor", attune:false, weight:13, desc:"Клёпаная кожа +1; бонусным действием меняет внешний вид одежды." },
  { id:"demon-armor",             name:"Демонический доспех",               nameEn:"Demon Armor",                       rarity:"very_rare", type:"armor", attune:true,  weight:65, desc:"Латы +1 с когтистыми кулаками; но привязывает к демонической воле." },
  { id:"animated-shield",         name:"Живой щит",                         nameEn:"Animated Shield",                   rarity:"very_rare", type:"shield", attune:true, weight:6, desc:"Бонусным действием парит и защищает вас без рук на 1 минуту." },
  { id:"spellguard-shield",       name:"Щит от заклинаний",                 nameEn:"Spellguard Shield",                 rarity:"very_rare", type:"shield", attune:true, weight:6, desc:"Помеха атакующим заклинаниям по вам; преимущество на спасы от заклинаний." },
  { id:"arrow-catching-shield",   name:"Ловящий стрелы щит",                nameEn:"Arrow-Catching Shield",             rarity:"rare",      type:"shield", attune:true, weight:6, desc:"+2 КД против дальнобойных атак; притягивает к себе выстрелы по соседям." },

  // ─── Чудесные предметы (Wondrous Items) ───────────────────────────────────
  { id:"bag-of-holding",          name:"Сумка хранения",                    nameEn:"Bag of Holding",                    rarity:"uncommon",  type:"wondrous", attune:false, weight:15, desc:"Вмещает до 250 кг / 2 м³, весит всегда 7 кг." },
  { id:"bag-of-tricks",           name:"Сумка фокусов",                     nameEn:"Bag of Tricks",                     rarity:"uncommon",  type:"wondrous", attune:false, weight:0.5, desc:"Доставайте пушистый шарик — он превращается в зверя-союзника." },
  { id:"handy-haversack",         name:"Удобный рюкзак Хеварда",            nameEn:"Heward's Handy Haversack",          rarity:"rare",      type:"wondrous", attune:false, weight:5, desc:"Три кармана-измерения; нужный предмет всегда оказывается сверху." },
  { id:"portable-hole",           name:"Переносная дыра",                   nameEn:"Portable Hole",                     rarity:"rare",      type:"wondrous", attune:false, weight:0, desc:"Тканевый круг, открывающий пространство-яму 3 м глубиной." },
  { id:"cloak-of-protection",     name:"Плащ защиты",                       nameEn:"Cloak of Protection",               rarity:"uncommon",  type:"wondrous", attune:true,  weight:1, desc:"+1 к КД и ко всем спасброскам." },
  { id:"cloak-of-elvenkind",      name:"Эльфийский плащ",                   nameEn:"Cloak of Elvenkind",                rarity:"uncommon",  type:"wondrous", attune:true,  weight:1, desc:"Преимущество на Скрытность; помеха тем, кто пытается вас заметить." },
  { id:"cloak-of-displacement",   name:"Плащ ускользания",                  nameEn:"Cloak of Displacement",             rarity:"rare",      type:"wondrous", attune:true,  weight:1, desc:"Создаёт иллюзию смещения: помеха первой атаке по вам каждый ход." },
  { id:"cloak-of-the-bat",        name:"Плащ летучей мыши",                 nameEn:"Cloak of the Bat",                  rarity:"rare",      type:"wondrous", attune:true,  weight:1, desc:"Преимущество на Скрытность; в темноте можно летать или стать мышью." },
  { id:"cloak-of-arachnida",      name:"Плащ паука",                        nameEn:"Cloak of Arachnida",                rarity:"very_rare", type:"wondrous", attune:true,  weight:1, desc:"Хождение по стенам, сопротивление яду, иммунитет к паутине, заклинание паутины." },
  { id:"boots-of-elvenkind",      name:"Эльфийские сапоги",                 nameEn:"Boots of Elvenkind",                rarity:"uncommon",  type:"wondrous", attune:false, weight:1, desc:"Преимущество на бесшумное передвижение (Скрытность)." },
  { id:"boots-of-striding-springing",name:"Сапоги ходьбы и прыжков",        nameEn:"Boots of Striding and Springing",   rarity:"uncommon",  type:"wondrous", attune:true,  weight:1, desc:"Скорость не снижается ничем; прыжки утраиваются." },
  { id:"boots-of-speed",          name:"Сапоги скорости",                   nameEn:"Boots of Speed",                    rarity:"rare",      type:"wondrous", attune:true,  weight:1, desc:"Бонусным действием удваиваете скорость и навязываете помеху атакам по вам." },
  { id:"boots-of-levitation",     name:"Сапоги левитации",                  nameEn:"Boots of Levitation",               rarity:"rare",      type:"wondrous", attune:true,  weight:1, desc:"По желанию накладываете на себя «Левитацию»." },
  { id:"winged-boots",            name:"Крылатые сапоги",                   nameEn:"Winged Boots",                      rarity:"uncommon",  type:"wondrous", attune:true,  weight:1, desc:"Скорость полёта, равная вашей; до 4 часов полёта на заряд." },
  { id:"amulet-of-health",        name:"Амулет здоровья",                   nameEn:"Amulet of Health",                  rarity:"rare",      type:"wondrous", attune:true,  weight:0, desc:"Телосложение становится 19." },
  { id:"amulet-proof-detection",  name:"Амулет защиты от обнаружения и поиска", nameEn:"Amulet of Proof against Detection", rarity:"uncommon",  type:"wondrous", attune:true,  weight:0, desc:"Вас нельзя обнаружить или подслушать магией прорицания." },
  { id:"amulet-of-the-planes",    name:"Амулет планов",                     nameEn:"Amulet of the Planes",              rarity:"very_rare", type:"wondrous", attune:true,  weight:0, desc:"Накладывает «Перемещение между планами» (рискованно без точного описания)." },
  { id:"periapt-wound-closure",   name:"Медальон затягивающихся ран",       nameEn:"Periapt of Wound Closure",          rarity:"uncommon",  type:"wondrous", attune:true,  weight:0, desc:"Стабильны при 0 хитах; восстановление кубиками хитов удваивается." },
  { id:"periapt-proof-poison",    name:"Медальон защиты от яда",            nameEn:"Periapt of Proof against Poison",   rarity:"rare",      type:"wondrous", attune:true,  weight:0, desc:"Иммунитет к яду и состоянию «отравление»." },
  { id:"belt-dwarvenkind",        name:"Пояс дварфов",                      nameEn:"Belt of Dwarvenkind",               rarity:"rare",      type:"wondrous", attune:true,  weight:0, desc:"+2 Тел, преимущество против яда, тёмное зрение и дружелюбие дварфов." },
  { id:"belt-giant-strength-hill",name:"Пояс силы холмовых великанов",      nameEn:"Belt of Hill Giant Strength",       rarity:"rare",      type:"wondrous", attune:true,  weight:0, desc:"Сила становится 21." },
  { id:"belt-giant-strength-stone",name:"Пояс силы каменных великанов",     nameEn:"Belt of Stone Giant Strength",      rarity:"very_rare", type:"wondrous", attune:true,  weight:0, desc:"Сила становится 23." },
  { id:"belt-giant-strength-fire",name:"Пояс силы огненных великанов",      nameEn:"Belt of Fire Giant Strength",       rarity:"very_rare", type:"wondrous", attune:true,  weight:0, desc:"Сила становится 25." },
  { id:"belt-giant-strength-cloud",name:"Пояс силы облачных великанов",     nameEn:"Belt of Cloud Giant Strength",      rarity:"legendary", type:"wondrous", attune:true,  weight:0, desc:"Сила становится 27." },
  { id:"belt-giant-strength-storm",name:"Пояс силы штормовых великанов",    nameEn:"Belt of Storm Giant Strength",      rarity:"legendary", type:"wondrous", attune:true,  weight:0, desc:"Сила становится 29." },
  { id:"bracers-of-defense",      name:"Наручи защиты",                     nameEn:"Bracers of Defense",                rarity:"rare",      type:"wondrous", attune:true,  weight:0, desc:"+2 КД, если без доспеха и щита." },
  { id:"bracers-of-archery",      name:"Наручи стрельбы из лука",           nameEn:"Bracers of Archery",                rarity:"uncommon",  type:"wondrous", attune:true,  weight:0, desc:"Владение длинным/коротким луком и +2 к урону их выстрелами." },
  { id:"brooch-of-shielding",     name:"Брошь защиты",                      nameEn:"Brooch of Shielding",               rarity:"uncommon",  type:"wondrous", attune:true,  weight:0, desc:"Сопротивление силовому урону; иммунитет к «Волшебной стреле»." },
  { id:"gauntlets-ogre-power",    name:"Рукавицы силы огра",                nameEn:"Gauntlets of Ogre Power",           rarity:"uncommon",  type:"wondrous", attune:true,  weight:0, desc:"Сила становится 19." },
  { id:"gloves-missile-snaring",  name:"Перчатки ловли снарядов",           nameEn:"Gloves of Missile Snaring",         rarity:"uncommon",  type:"wondrous", attune:true,  weight:0, desc:"Реакцией снижаете урон от дальнобойной атаки, иногда ловите снаряд." },
  { id:"gloves-swimming-climbing",name:"Перчатки плавания и лазания",       nameEn:"Gloves of Swimming and Climbing",   rarity:"uncommon",  type:"wondrous", attune:true,  weight:0, desc:"Лазание/плавание не стоят лишнего; +5 к таким проверкам." },
  { id:"gloves-of-thievery",      name:"Перчатки воровства",                nameEn:"Gloves of Thievery",                rarity:"uncommon",  type:"wondrous", attune:false, weight:0, desc:"+5 к Ловкости рук и вскрытию замков." },
  { id:"headband-of-intellect",   name:"Повязка интеллекта",                nameEn:"Headband of Intellect",             rarity:"uncommon",  type:"wondrous", attune:true,  weight:0, desc:"Интеллект становится 19." },
  { id:"goggles-of-night",        name:"Ночные очки",                       nameEn:"Goggles of Night",                  rarity:"uncommon",  type:"wondrous", attune:false, weight:0, desc:"Тёмное зрение на 18 м (или +18 м к имеющемуся)." },
  { id:"eyes-of-the-eagle",       name:"Очки орлиного зрения",              nameEn:"Eyes of the Eagle",                 rarity:"uncommon",  type:"wondrous", attune:true,  weight:0, desc:"Преимущество на Внимательность (зрение)." },
  { id:"eyes-of-charming",        name:"Очки очарования",                   nameEn:"Eyes of Charming",                  rarity:"uncommon",  type:"wondrous", attune:true,  weight:0, charges:3, desc:"3 заряда: «Очарование личности» взглядом (Мдр)." },
  { id:"hat-of-disguise",         name:"Шапка маскировки",                  nameEn:"Hat of Disguise",                   rarity:"uncommon",  type:"wondrous", attune:true,  weight:0, desc:"По желанию накладываете на себя «Изменение внешности»." },
  { id:"helm-comprehend-languages",name:"Шлем понимания языков",            nameEn:"Helm of Comprehending Languages",   rarity:"uncommon",  type:"wondrous", attune:false, weight:3, desc:"По желанию накладываете «Понимание языков»." },
  { id:"helm-of-telepathy",       name:"Шлем телепатии",                    nameEn:"Helm of Telepathy",                 rarity:"uncommon",  type:"wondrous", attune:true,  weight:3, desc:"Читаете мысли и мысленно общаетесь; заряды на «Внушение»." },
  { id:"helm-of-teleportation",   name:"Шлем телепортации",                 nameEn:"Helm of Teleportation",             rarity:"rare",      type:"wondrous", attune:true,  weight:3, charges:3, desc:"3 заряда: накладывает «Телепортация»." },
  { id:"helm-of-brilliance",      name:"Шлем блеска",                       nameEn:"Helm of Brilliance",                rarity:"very_rare", type:"wondrous", attune:true,  weight:3, desc:"Самоцветы дают огненные/радиантные заклинания и сияние против нежити." },
  { id:"necklace-of-fireballs",   name:"Ожерелье огненных шаров",           nameEn:"Necklace of Fireballs",             rarity:"rare",      type:"wondrous", attune:false, weight:0, desc:"Сорвите шарик и бросьте — взрывается «Огненным шаром»." },
  { id:"necklace-of-adaptation",  name:"Ожерелье адаптации",                nameEn:"Necklace of Adaptation",            rarity:"uncommon",  type:"wondrous", attune:true,  weight:0, desc:"Дышите нормально в любой среде; преимущество против вредных газов." },
  { id:"necklace-prayer-beads",   name:"Ожерелье молитвенных чёток",        nameEn:"Necklace of Prayer Beads",          rarity:"rare",      type:"wondrous", attune:true,  weight:0, desc:"Магические бусины дают заклинания (благословение, лечение и пр.)." },
  { id:"pearl-of-power",          name:"Жемчужина силы",                    nameEn:"Pearl of Power",                    rarity:"uncommon",  type:"wondrous", attune:true,  weight:0, desc:"1 раз в день бонусным действием восстанавливаете ячейку ≤3 уровня." },
  { id:"stone-of-good-luck",      name:"Камень удачи",                      nameEn:"Stone of Good Luck (Luckstone)",    rarity:"uncommon",  type:"wondrous", attune:true,  weight:0, desc:"+1 ко всем проверкам характеристик и спасброскам." },
  { id:"medallion-of-thoughts",   name:"Медальон мыслей",                   nameEn:"Medallion of Thoughts",             rarity:"uncommon",  type:"wondrous", attune:true,  weight:0, charges:3, desc:"3 заряда: накладывает «Обнаружение мыслей»." },
  { id:"slippers-spider-climbing",name:"Туфли паука",                       nameEn:"Slippers of Spider Climbing",       rarity:"uncommon",  type:"wondrous", attune:true,  weight:0, desc:"Хождение по стенам и потолку со скоростью лазания." },
  { id:"winged-cloak",            name:"Плащ ската",                        nameEn:"Cloak of the Manta Ray",            rarity:"uncommon",  type:"wondrous", attune:false, weight:1, desc:"Под водой даёт подводное дыхание и скорость плавания 18 м." },
  { id:"decanter-endless-water",  name:"Графин бесконечной воды",           nameEn:"Decanter of Endless Water",         rarity:"uncommon",  type:"wondrous", attune:false, weight:2, desc:"Выливает по команде струю, поток или гейзер пресной воды." },
  { id:"driftglobe",              name:"Парящая сфера",                     nameEn:"Driftglobe",                        rarity:"uncommon",  type:"wondrous", attune:false, weight:1, desc:"Стеклянный шар, парящий рядом и дающий свет («Свет»/«Огонёк маяка»)." },
  { id:"rope-of-climbing",        name:"Верёвка лазания",                   nameEn:"Rope of Climbing",                  rarity:"uncommon",  type:"wondrous", attune:false, weight:3, desc:"18-метровая верёвка двигается по команде, вяжет узлы и крепится сама." },
  { id:"sending-stones",          name:"Камни послания",                    nameEn:"Sending Stones",                    rarity:"uncommon",  type:"wondrous", attune:false, weight:1, desc:"Пара камней; 1 раз в день связь как заклинанием «Послание»." },
  { id:"figurine-wondrous-power", name:"Статуэтка чудесной силы",           nameEn:"Figurine of Wondrous Power",        rarity:"rare",      type:"wondrous", attune:false, weight:1, desc:"Статуэтка оживает в зверя-союзника (серебряный ворон, ониксовый пёс и т.п.)." },
  { id:"horn-of-blasting",        name:"Рог взрыва",                        nameEn:"Horn of Blasting",                  rarity:"rare",      type:"wondrous", attune:false, weight:2, desc:"Действием издаёт громовой конус: 5к6 грома и 5к6 урона, оглушение." },
  { id:"horn-of-valhalla",        name:"Рог Валгаллы",                      nameEn:"Horn of Valhalla",                  rarity:"rare",      type:"wondrous", attune:false, weight:2, desc:"Призывает духов-берсерков на помощь в бою." },
  { id:"robe-of-useful-items",    name:"Мантия полезных предметов",         nameEn:"Robe of Useful Items",              rarity:"uncommon",  type:"wondrous", attune:false, weight:1, desc:"Нашивки отрываются и становятся предметами (факел, лестница, лодка и т.п.)." },
  { id:"robe-of-eyes",            name:"Мантия глаз",                       nameEn:"Robe of Eyes",                      rarity:"rare",      type:"wondrous", attune:true,  weight:1, desc:"Видите во всех направлениях, в темноте и невидимое; уязвимы к яркому свету." },
  { id:"robe-of-the-archmagi",    name:"Мантия архимага",                   nameEn:"Robe of the Archmagi",              rarity:"legendary", type:"wondrous", attune:true,  weight:0, desc:"Базовый КД 15+Лов, преимущество на спасы от заклинаний, +2 к Сл и атакам заклинаниями." },
  { id:"ioun-stone-mastery",      name:"Камень Йоун (мастерство)",          nameEn:"Ioun Stone of Mastery",             rarity:"legendary", type:"wondrous", attune:true,  weight:0, desc:"Парящий камень; +1 к бонусу мастерства." },
  { id:"ioun-stone-protection",   name:"Камень Йоун (защита)",              nameEn:"Ioun Stone of Protection",          rarity:"rare",      type:"wondrous", attune:true,  weight:0, desc:"Парящий камень даёт +1 к КД." },
  { id:"ioun-stone-fortitude",    name:"Камень Йоун (стойкость)",           nameEn:"Ioun Stone of Fortitude",           rarity:"very_rare", type:"wondrous", attune:true,  weight:0, desc:"Парящий камень; Телосложение +2 (максимум 20)." },
  { id:"deck-of-many-things",     name:"Колода многих вещей",               nameEn:"Deck of Many Things",               rarity:"legendary", type:"wondrous", attune:false, weight:0, desc:"Каждая вытянутая карта несёт мощный благой или катастрофический эффект." },
  { id:"sphere-of-annihilation",  name:"Сфера аннигиляции",                 nameEn:"Sphere of Annihilation",            rarity:"legendary", type:"wondrous", attune:false, weight:0, desc:"Шар тьмы 0,6 м, уничтожающий всё, что касается; управляется усилием воли." },
  { id:"wings-of-flying",         name:"Крылья полёта",                     nameEn:"Wings of Flying",                   rarity:"rare",      type:"wondrous", attune:true,  weight:0, desc:"Плащ превращается в крылья: скорость полёта 18 м на время." }
];
